### ISSUE TITLE
Latest version 1.24.8 under OS X 10.14.6 Mojave 

### ISSUE THREAD

**Issue by alejoduque** [jameshball/osci-render#78] opened 2022-06-03 15:40 UTC
Hello James,
Here trying the latest version, after installing and double clicking, it wont open, one can hear the sound of the basic model but nothing comes on the screen and the this bug report appears:

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'not running on AppKit (main) thread'
terminating with uncaught exception of type NSException
abort() called

I had one of the earlier versions installed before, not sure which  one now since i think it got replaced by the installer. Is there anything i need to remove via command line to start from zero?

Please let me know what else I should tell you to help debug.

Alejo

**Comment by jameshball** [comment] 2022-06-03 16:00
Thanks for reporting the issue! I think you should be able to find the program in Finder by searching in Spotlight and then opening in Finder. From there you should be able to move it to the trash.

It would be really helpful if you could install Java 17 from [here](https://www.oracle.com/java/technologies/downloads) (making sure you select Java 17 rather than 18) and then run the `osci-render-mac-1.24.8.jar` file for [v1.24.8](https://github.com/jameshball/osci-render/releases/tag/v1.24.8) by opening a terminal where the `.jar` is downloaded to, and running `java -jar osci-render-mac-1.24.8.jar` to start osci-render. If you could then send me the output from the terminal after running that would be great!

Additionally, could you try [v1.24.7](https://github.com/jameshball/osci-render/releases/tag/v1.24.7) please (either the `.jar` or installing it as you have before) and see if you get the same problem there?

Please let me know if you have any issues with this!

Thanks!

**Comment by jameshball** [comment] 2022-06-03 16:37
If v1.24.7 also doesn't work, it would be very useful to download the `.jar` files for [previous releases](https://github.com/jameshball/osci-render/releases) until you find the first version that works. Thank you!

**Comment by alejoduque** [comment] 2022-06-03 19:35
12.24.7 didnt work. Will try what you suggest and report back, thanks!

**Comment by jameshball** [comment] 2022-06-03 20:18
Thanks for providing this! Apologies for my lack of experience with JACK but is there any way you can try this without using JACK? There are some details about this error here - is it worth trying any of this? https://askubuntu.com/questions/557906/problem-starting-jack-server-jack-server-is-not-running-or-cannot-be-started

Could you try earlier jars in the terminal and see if you get the same error?

**Comment by alejoduque** [comment] 2022-06-04 20:05
Hello, i had errors with all this versions:
osci-render-mac-1.20.0.jar  osci-render-mac-1.24.5.jar  osci-render-mac-1.24.7.jar  
osci-render-mac-1.18.3.jar  osci-render-mac-1.24.3.jar  osci-render-mac-1.24.6.jar  osci-render-mac-1.24.8.jar 

Only this one opened:
java -jar osci-render-mac-1.15.0.jar 
Jun 04, 2022 3:02:10 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @12cc3010'
dlopen error : dlopen(libjack.0.dylib, 1): image not found 

Perhaps in between version 15 and 18 one other will also open, but didnt tried 16 o 17.. yet

**Comment by alejoduque** [comment] 2022-06-04 20:06
ohh and i was only trying to open the app, no test with jack running where perfomed until you mentioned it.. and chnaged nothing software will crash

**Comment by jameshball** [comment] 2022-06-04 20:48
Thanks for testing those! I think this might be an issue with JACK on OSX. https://github.com/jackaudio/jack2/issues/733 Seems to suggest that this is an issue with the JACK install through homebrew, instead of installing with the official installer?

First of all, could you try running `jackd -V` in terminal to see what version of JACK you have, and then reply with the output.

If you have JACK installed through homebrew, could you try uninstalling it with `brew uninstall jack`? You could then try and run osci-render again to see if JACK is causing the issue.

If that works, you could try installing the latest version of JACK with the official installer [here](https://jackaudio.org/downloads/) and then re-run to see if that fixes anything.

Thanks!

**Comment by alejoduque** [comment] 2022-06-04 22:27
I have done this:

(base) dspstv-2:vectrex a$ brew uninstall jack
Uninstalling /usr/local/Cellar/jack/1.9.19... (85 files, 3.8MB)

Installed the latest one from the website but get same issues. Crash on opening. Jack via Qjackctl runs normal using the default internal sound card from the computer.

**Comment by jameshball** [comment] 2022-06-05 07:23
Thanks - I'm gonna continue looking into this.

I've just confirmed on another mac that this isn't a widespread issue affecting all macs so I will remove the warning and pre-release statement from v1.24.8

Just to confirm, do you always hear audio whenever you start the program but the interface doesn't show at all?

Also, since you first downloaded osci-render have you upgraded your version of macos or made any other big changes to your computer?

**Comment by alejoduque** [comment] 2022-06-09 17:34
Hello again James, to answer your questions.. i have not changed OS (no big changes, removed jack through brew) and I do hear the audio sound at start half of the attempts to open. With o without jack running.

**Comment by jameshball** [comment] 2023-12-22 18:31
Closing this as I've just released osci-render 2.0 which is a complete rewrite of osci-render from scratch and should solve this problem! You can get it [here](https://osci-render.com) :)

**Closed by jameshball** 2023-12-22 18:31 UTC
Labels: bug, help wanted
