### ISSUE TITLE
JACK audio/MIDI/CV?

### ISSUE THREAD

**Issue by mxmilkiib** [jameshball/osci-render#52] opened 2022-03-22 13:00 UTC
A JACK audio (and MIDI) backend would provide Linux support (though JACK is cross-platform itself).

JACK also has a CV port metadata feature, which I guess could be utilised.

**Comment by jameshball** [comment] 2022-03-22 13:30
Thanks for the feedback! Would you be able to clarify a bit what you'd like to be added? I've used JACK a bit but not massively and doing any low-latency audio on Linux has proven to be a pain.

Linux should be supported just fine at the moment, albeit with higher latency than Mac/Windows - if you are having issues with that could you send me a screenshot of the devices menu dropdown?

**Comment by mxmilkiib** [comment] 2022-03-22 14:09
Ah, great on Linux support! I'm away from my computer at the moment. I'm taking about possibly adding a native JACK client backend. JACK has not got the best documentation, especially about it's ecosystem and the things that make it easier to use. While everyone's milage may vary, benefits over the other audio backends listed in the README are that it's not licence encumbered *and* it's open source *and* multiplatform. It also has its metadata system that allows for CV ports (older) and MIDNAM (newer). Plus many apps and clients to interact with the JACK graph with. N.b if you might like any JACK development assistance, #jack n #lad on libera.

**Comment by jameshball** [comment] 2022-06-05 07:26
Hi, unfortunately I don't have any update on specific support for JACK, but I was wondering if you've experienced any issues similar to those being faced in #78 ?

I'm currently trying to work out whether the issue is related to JACK or whether it's something completely different.

Thank you!

**Comment by jameshball** [comment] 2023-12-22 18:32
Closing this as I've just released osci-render 2.0 which is a complete rewrite of osci-render from scratch as an audio plugin and should solve this problem! You can get it [here](https://osci-render.com) :)

**Closed by jameshball** 2023-12-22 18:32 UTC
